version: "3"

services:
  gcs:
    image: fsouza/fake-gcs-server
    command: -scheme both -port-http 8001 -public-host ${URL:-localhost}:8001
    ports:
      - "4443:4443"
      - "8001:8001"
    volumes:
      - ./data:/storage
    restart: always
    container_name: gcs
    networks:
      - custom_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    volumes:
      - ./mongodb/initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb-data:/data/db/
      - mongodb-log:/var/log/mongodb/
    ports:
      - "27017:27017"
    networks:
      - custom_network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    ports:
      - 8081:8081
    networks:
      - custom_network
    depends_on:
      - mongodb

volumes:
  mongodb-data:
    driver: local
    name: mongo-data
  mongodb-log:
    driver: local
    name: mongo-log

networks:
  custom_network:
    external: true
